### ISSUE TITLE
运行train.py时出现没有datasets/Market/pytorch/val下的class的error

### ISSUE THREAD

**Issue by Pinoeer-kingxi** [finger-monkey/LTA_and_joint-defence#2]
运行train.py时出现没有datasets/Market/pytorch/val下的class的error，像是prepare.py缺失val目录下class的生成。想请问作者怎么划分的，怎么生成val的

**Comment by finger-monkey** [comment]
你好，时间有点久远我已经忘记了。之前版本管理比较混乱，一些版本有这个问题。可能这个版本是没有修正过来的。就目前考虑一下，你也许可以将数据分成两批来解决。

**Comment by Pinoeer-kingxi** [comment]
感谢作者抽空解答！还想请问作者，numpy和pytorch的版本多少。感谢作者的时间！

**Comment by finger-monkey** [comment]
参考 https://github.com/layumi/Person_reID_baseline_pytorch

**Comment by finger-monkey** [comment]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/random_erasing.py， 其中LTA攻击中的随机灰度化是我们在另外一篇论文提出来的，代码可以在https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/random_erasing.py%20%20%20%20RandomGrayscaleErasing  这里找到。我们的攻击基于上面的baseline开发。

**Comment by Pinoeer-kingxi** [comment]
好的，非常感谢作者的分享，谢谢您，我先去看看
